artifact_location: file:C:/Users/Sujana/Desktop/PRO/runs/mlflow/288904613344293356
creation_time: 1742180099128
experiment_id: '288904613344293356'
last_update_time: 1742180099128
lifecycle_stage: active
name: C:/Users/Sujana/Desktop/PROJECT NEW 10/YOLOv3_Custom/
